package telas;

import classes.ControladorPlayer;
import classes.Musica;
import classes.Play;
import classes.Track;
import java.io.File;
import javax.swing.ImageIcon;

public class JFControlMusic extends javax.swing.JFrame {

    ImageIcon img = null;
    boolean flag;

    String pathMusica;
    final String PATH = "musicas/";
    final String EXTENSAO = ".mp3";

    File m = null;
    Track track = null;
    Play play = null;
    ControladorPlayer cp = null;

    public JFControlMusic(Musica musica) {
        initComponents();
        ImageIcon img1 = new ImageIcon("imagens/pause_icon.png");
        ImageIcon img2 = new ImageIcon("imagens/stop_icon.png");

        btn1.setIcon(img1);
        btn2.setIcon(img2);

        pathMusica = PATH + musica.getTitulo() + EXTENSAO;
        tocar(pathMusica);
    }

    public void tocar(String pathMusica) {
        m = new File(pathMusica);
        track = new Track(m);
        play = new Play(track);
        cp = new ControladorPlayer(play);
        cp.tocarMusica();
        cp.tocarMusica();
    }

    public void pausar() {
        cp.pausarMusica();
    }

    public void parar() {
        cp.pararMusica();
    }

    public void continuar() {
        cp.continuarMusica();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("MÚSICA:");

        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btnSair.setText("SAIR");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSair)
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn1, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnSair)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        parar();
        img = new ImageIcon("imagens/play_icon.png");
        btn1.setIcon(img);
        flag = true;
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        String[] p = btn1.getIcon().toString().split("/");
        if (p[1].equals("pause_icon.png")) {
            img = new ImageIcon("imagens/play_icon.png");
            btn1.setIcon(img);
            pausar();
        } else {
            if (!flag) {
                img = new ImageIcon("imagens/pause_icon.png");
                btn1.setIcon(img);
                continuar();
            } else {
                img = new ImageIcon("imagens/pause_icon.png");
                btn1.setIcon(img);
                tocar(pathMusica);
            }

        }

    }//GEN-LAST:event_btn1ActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        parar();
        setVisible(false);
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
