
package telas;

import classes.Musica;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


public class JFDadosPlayList extends javax.swing.JFrame {

    /**
     * Creates new form JFDadosPlayList
     */
    ArrayList<Musica> musicas = null;
    int tempo = 0;
    public JFDadosPlayList() {
        initComponents();
        play.setText(play.getText() + " "+JFPlayList.pl.getNome());
        user.setText(user.getText() + " "+JFUsuario.user.getNome());
        this.musicas = JFPlayList.pl.listar();
        duracaoTxt.setVisible(false);
        listarMusicas(musicas);
    }
    
    
    public void listarMusicas(ArrayList<Musica> list){
        String colunas = "ID:\t"+"NOME:\t"+"DURAÇÃO:\t"+"GÊNERO:\n";
        jtxLista.setText(colunas);
        for(int i=0; i < list.size(); i++){
            String linha = list.get(i).getId()+"\t"+list.get(i).getTitulo()+"\t"+
                    list.get(i).getDuracao()+"\t"+list.get(i).getGenero().getNome()+"\n";
            jcbMusicas.addItem(String.valueOf(list.get(i).getId()));
            jtxLista.append(linha);
        }
        jtxLista.setEnabled(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        play = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxLista = new javax.swing.JTextArea();
        btnDuracao = new javax.swing.JButton();
        duracaoTxt = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        jcbMusicas = new javax.swing.JComboBox<>();
        btnTocar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        back = new javax.swing.JButton();

        jScrollPane2.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        play.setText("MÚSICAS DA PLAY LIST : ");

        jtxLista.setColumns(20);
        jtxLista.setRows(5);
        jScrollPane1.setViewportView(jtxLista);

        btnDuracao.setText("DURAÇÃO");
        btnDuracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDuracaoActionPerformed(evt);
            }
        });

        duracaoTxt.setText("jLabel2");

        user.setText("USUÁRIO:");

        jcbMusicas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID MÚSICA" }));

        btnTocar.setText("TOCAR");
        btnTocar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTocarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setText("SELECIONE:");

        back.setText("VOLTAR");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jcbMusicas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTocar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDuracao)
                                .addGap(18, 18, 18)
                                .addComponent(duracaoTxt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(back))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(324, 324, 324))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(play)
                            .addGap(227, 227, 227)))
                    .addComponent(user))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(play)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(user)
                .addGap(8, 8, 8)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbMusicas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTocar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDuracao)
                    .addComponent(duracaoTxt)
                    .addComponent(back))
                .addGap(25, 25, 25))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDuracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDuracaoActionPerformed
        tempo = JFPlayList.pl.calcularDuracao();
        String formatacao = null;
        if(tempo > 1440){
           int d = tempo/1440; 
           int h = (tempo - (d*1440))/60;
           int m = tempo - (((tempo - (d*1440))/60)*60); 
           formatacao = d+" dias,"+h+" horas,"+m+" minutos";
        }else{
           int h = tempo/60;
           int m = tempo - (h*60); 
           int s = (tempo * 60) - ((h*60*60)+(m*60));
           formatacao = 0+" dias,"+h+" horas,"+m+" minutos"; 
        }
        
        duracaoTxt.setText(formatacao);
        duracaoTxt.setVisible(true);
    }//GEN-LAST:event_btnDuracaoActionPerformed

    private void btnTocarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTocarActionPerformed
        int index = jcbMusicas.getSelectedIndex();
        
        if(index != 0){
            Musica musica = musicas.get(index - 1);
            setVisible(false);
            new JFControlMusic(musica).setVisible(true);
        }else{
           JOptionPane.showMessageDialog(this, "SELECIONE UMA MÚSICA !");
        }
        
    }//GEN-LAST:event_btnTocarActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton btnDuracao;
    private javax.swing.JButton btnTocar;
    private javax.swing.JLabel duracaoTxt;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JComboBox<String> jcbMusicas;
    private javax.swing.JTextArea jtxLista;
    private javax.swing.JLabel play;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
