package telas;

import classes.Genero;
import classes.Musica;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class JFMusica extends javax.swing.JFrame {

    /**
     * Creates new form JFMusica
     */
    boolean flag;

    public JFMusica(boolean flag) {
        initComponents();
        this.flag = flag;
        if (this.flag) {
            jFrameRemover();
        } else {
            lRem.setVisible(false);
            idRem.setVisible(false);
        }
    }

    public final void jFrameRemover() {
        setSize(300, 180);

        t.setVisible(false);
        i.setVisible(false);
        d.setVisible(false);
        g.setVisible(false);
        idGenero.setVisible(false);
        lRem.setVisible(true);

        ctTitulo.setVisible(false);
        ctId.setVisible(false);
        ctDuracao.setVisible(false);
        ctGenero.setVisible(false);
        ctIdGenero.setVisible(false);
        idRem.setVisible(true);

        btn.setText("REMOVER");
        btn.setVisible(true);
        btn2.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        t = new javax.swing.JLabel();
        i = new javax.swing.JLabel();
        d = new javax.swing.JLabel();
        btn = new javax.swing.JButton();
        ctTitulo = new javax.swing.JTextField();
        ctId = new javax.swing.JTextField();
        ctDuracao = new javax.swing.JTextField();
        g = new javax.swing.JLabel();
        ctGenero = new javax.swing.JTextField();
        idGenero = new javax.swing.JLabel();
        ctIdGenero = new javax.swing.JTextField();
        btn2 = new javax.swing.JButton();
        lRem = new javax.swing.JLabel();
        idRem = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("MÚSICA");

        t.setText("TITULO:");

        i.setText("ID:");

        d.setText("DURAÇÃO (min):");

        btn.setText("CADASTRAR");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        g.setText("GÊNERO:");

        ctGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctGeneroActionPerformed(evt);
            }
        });

        idGenero.setText("ID:");

        ctIdGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctIdGeneroActionPerformed(evt);
            }
        });

        btn2.setText("VOLTAR");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        lRem.setText("ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(d)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ctDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(g)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ctGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(t)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ctTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lRem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idRem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(i)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ctId, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(idGenero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ctIdGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btn)
                .addGap(42, 42, 42)
                .addComponent(btn2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t)
                    .addComponent(ctTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(i)
                    .addComponent(ctId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lRem)
                    .addComponent(idRem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d)
                    .addComponent(ctDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(g)
                    .addComponent(ctGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idGenero)
                    .addComponent(ctIdGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn)
                    .addComponent(btn2))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public Musica inserir() {
        String t = ctTitulo.getText();
        int id = Integer.parseInt(ctId.getText());
        int d = Integer.parseInt(ctDuracao.getText());

        String gt = ctGenero.getText();
        int idG = Integer.parseInt(ctIdGenero.getText());

        Genero g = new Genero(idG, gt);
        Musica m = new Musica(id, t, d, g);

        return m;
    }

    public Musica remover() {
        if (idRem.getText().trim() != null) {
            int id = Integer.parseInt(idRem.getText().trim());

            Genero g = new Genero(0, null);
            Musica m = new Musica(id, null, 0, g);
            return m;

        }

        return null;
    }
    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        boolean res = false;

        if (flag) {
            try {
                //REM
                res = JFPlayList.pl.remover(remover());
                if (res == true) {
                    JOptionPane.showMessageDialog(this, "Música removida da playlist !");
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao tentar remover música! Verifique os dados da mesma.");
                }
            } catch (IOException ex) {
                Logger.getLogger(JFMusica.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            //ADD
            res = JFPlayList.pl.inserir(inserir());
            if (res == true) {
                JOptionPane.showMessageDialog(this, "Música inserida na playlist !");
            } else {
                JOptionPane.showMessageDialog(this, "Já existe uma música com este ID !");
            }
        }

        limparCampos();

    }//GEN-LAST:event_btnActionPerformed

    private void ctGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctGeneroActionPerformed

    private void ctIdGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctIdGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctIdGeneroActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btn2ActionPerformed

    public void limparCampos() {
        ctTitulo.setText("");
        ctId.setText("");
        ctDuracao.setText("");
        ctGenero.setText("");
        ctIdGenero.setText("");
        idRem.setText("");
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    private javax.swing.JButton btn2;
    private javax.swing.JTextField ctDuracao;
    private javax.swing.JTextField ctGenero;
    private javax.swing.JTextField ctId;
    private javax.swing.JTextField ctIdGenero;
    private javax.swing.JTextField ctTitulo;
    private javax.swing.JLabel d;
    private javax.swing.JLabel g;
    private javax.swing.JLabel i;
    private javax.swing.JLabel idGenero;
    private javax.swing.JTextField idRem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lRem;
    private javax.swing.JLabel t;
    // End of variables declaration//GEN-END:variables
}
